version: '3.8'
services:
    mysql:
        image: mariadb:latest
        ports: 
            - "3306:3306"
        env_file: 
            - ./env/mysql.env
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes: 
            - ./app:/var/www/html
    composer:
        build: 
            context: .
            dockerfile: dockerfiles/composer.dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - php
            - mysql
    nginx:
        build: 
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
    yarn:
        image: node:latest
        working_dir: /var/www/html
        command: ['/bin/bash', '-c', 'yarn install && yarn watch']
        depends_on:
            - php
        volumes:
            - ./app:/var/www/html
    adminer:
        image: adminer
        ports:
            - '8080:8080'
        depends_on:
            - php
            - mysql
        environment:
            ADMINER_DEFAULT_SERVER: 'mysql'
    postrun:
        build: 
            context: .
            dockerfile: dockerfiles/postrun.dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - composer
            - php
            - mysql