version: '3.8'
services:
    mysql:
        image: mariadb:latest
        ports: 
            - "3306:3306"
        env_file: 
            - ./env/mysql.env
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes: 
            - ./app:/var/www/html
    composer:
        build: 
            context: .
            dockerfile: dockerfiles/composer.dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - php
            - mysql
        # healthcheck:
            # test: ["CMD-SHELL", "curl -f http://localhost:8080"]
            # test: ["CMD", "curl", "-f", "http://localhost:8080"]
            # interval: 10s
            # timeout: 10s
            # retries: 3
            # start_period: 10s
    nginx:
        build: 
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
    yarn:
        build: 
            context: .
            dockerfile: dockerfiles/yarn.dockerfile
        depends_on:
            - php
        volumes:
            - ./app:/var/www/html
    adminer:
        image: adminer
        ports:
            - '8080:8080'
        depends_on:
            - php
            - mysql
        environment:
            ADMINER_DEFAULT_SERVER: 'mysql'
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "sleep 30s && http://localhost:8080"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        #     start_period: 40s
    postrun:
        build: 
            context: .
            dockerfile: dockerfiles/postrun.dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            composer:
                condition: service_started
            adminer:
                condition: service_started