version: '3.8'
services:
    mysql:
        image: mariadb:latest
        env_file: 
            - ./env/mysql.env
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        depends_on:
            - mysql
        volumes: 
            - ./app:/var/www/html
    yarn:
        image: node:latest
        working_dir: /var/www/html
        command: ['/bin/bash', '-c', 'yarn install && yarn watch']
        depends_on:
            - php
        volumes:
            - ./app:/var/www/html
    composer:
        build: 
            context: .
            dockerfile: dockerfiles/composer.dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - php
            - mysql
    webserver:
        build: 
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - php
            - mysql
    adminer:
        image: adminer
        ports:
            - '8080:8080'
        depends_on:
            - php
            - mysql
        environment:
            ADMINER_DEFAULT_SERVER: 'mysql'