fungio_google_map:
    map:
        # Map width
        width: "100%"

        # Map height
        height: "100vh"

        # google map Api language, default en
        language: de

        # Zoom of the map
        # If the autozoom flag is enabled, the zoom is not used
        zoom: 13

        api_key: '%env(FUNGIO_GOOGLE_MAP_API_KEY)%'
