security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto

    access_decision_manager:
        strategy: unanimous

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            logout:
                path: app_logout
                target: admin

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
