vich_uploader:
    db_driver: orm

    mappings:
        logos:
            uri_prefix: '/images/logos'
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: {chars_per_dir: '1', dirs: '2'}
